### ISSUE TITLE
Remove unused i18n files when language is dropped from config

### ISSUE THREAD

**Issue by maxprilutskiy** [replexica/replexica#127]
### What
Add a feature to the `replexica i18n` CLI that automatically removes extra i18n files when a supported language is removed from the i18n.json configuration.

### Why
- Keeps the project clean and organized
- Prevents confusion from outdated language files
- Reduces clutter in the codebase
- Saves disk/repo space (minor benefit)

### How
1. Compare the current i18n.json config with the existing i18n files
2. Identify files for languages no longer in the config
3. Remove the unused files

**Comment by RubenRuCh** [comment]
Great project!

I was thinking of building something similar, since for me it's a **pain** to keep updating all the languages when making significant changes in the docs. Glad I found Replexica, will for sure try it out in Opire (we use Nextra for our documentation)

I'm gonna create a small bounty for this issue if you don't mind @maxprilutskiy since I'll like to see this feature implemented

**Comment by opiredev** [comment]
@RubenRuCh created a $25.00 reward using [Opire](https://opire.dev) 
 <details><summary>How to earn this reward?</summary>

Since this project does not have Opire bot installed yet 😞 you need to go to [Opire](https://app.opire.dev) and claim the rewards through your programmer's dashboard once you have your PR ready 💪</details>

**Comment by mobley-trent** [comment]
Hey @maxprilutskiy @RubenRuCh I'm willing to give this a go

**Comment by mobley-trent** [comment]
Unrelated, but I'm currently running into this issue while building the codebase:

```
$ npm run build

> build
> turbo build

• Packages in scope: @replexica/cli, @replexica/compiler, @replexica/config, @replexica/demo/next-app, @replexica/react, @replexica/spec, replexica
• Running build in 7 packages
• Remote caching disabled
@replexica/spec:build: cache miss, executing 500815517a4b0692
  × internal errors encountered: unable to find package manager binary: cannot find binary
  │ path
```

It seems turbo is having issues locating npm. I've tried uninstalling and reinstalling to no avail. Just wondering if anyone ran into the same issue.
I'm running on Ubuntu Linux 22.04

**Comment by maxprilutskiy** [comment]
@mobley-trent let's see. can you try using pnpm, please, instead of npm?

We're using `pnpm`.

LMK if it won't help!

**Comment by maxprilutskiy** [comment]
@RubenRuCh ping me if you'd like to give it a try, and I'll give you access :)

**Comment by mobley-trent** [comment]
Hello @RubenRuCh kindly approve the bounty

**Comment by RubenRuCh** [comment]
Can you please [claim it](https://docs.opire.dev/overview/getting-started#create-a-pr-and-claim-the-reward)?

Since this repo doesn't have the bot installed, you need to do it directly from your [programmer's dashboard](https://app.opire.dev/dashboard/programmer/rewards)

<img width="617" alt="5486c726b2c71fd6c2440257ca03adde" src="https://github.com/user-attachments/assets/93359fc6-8cf9-47d9-91c3-341e9f85b965">


After you claim it, I will be able to process the payment

**Comment by opiredev** [comment]
🔥 The user @mobley-trent has claimed all rewards for this issue using [Opire](https://opire.dev).
🎯 You can see the PR [here](https://github.com/replexica/replexica/pull/140)
💰 @RubenRuCh you can pay the related rewards [here](https://app.opire.dev/dashboard/creator/rewards?platform=GitHub&platformId=2412772042)

**Comment by opiredev** [comment]
🥳 @RubenRuCh completed the payment of $25.00 in rewards for this issue 💰
The rewarded user is @mobley-trent - congratulations and thanks for your effort! 🎉
